### ISSUE TITLE
Public API of bp7 exposes UB to safe code

### ISSUE THREAD

**Issue by dtolnay** [dtn7/bp7-rs#2]
For example, the following safe program leads to bp7 performing Undefined Behavior:

```rust
// [dependencies]
// bp7 = "0.9.2"

fn main() {
    bp7::ffi::bundle_payload(0xdeadbeefusize as _);
}
```

```console
Segmentation fault (core dumped)
```

In general it is unsound for a safe API to result in UB.

**Comment by gh0st42** [comment]
Thank you for pointing this out!

I experimented with different alternatives but would would you suggest as the cleanest solution?

As a rust crate the whole FFI module is not needed and should not be used.
To create the headers using `cbindgen` the mentioned function must be made public. 
Thus, it appears also in the rust crate. 

Gating it behind a feature flag makes it a bit harder to accidentally misuse it but in the end the UB could still end up in rust  code.

Adding `unsafe` to all functions pleases clippy but should not `extern "C"` already imply that it is unsafe or contains potential UB?
